#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

export MA_NATIVE_CAPTURE_SMOKE=1
export MA_NATIVE_CAPTURE_RELEASE_SCOPE=1
export MA_NATIVE_CAPTURE_ARTIFACT_SMOKE_ATTEMPTS="${MA_NATIVE_CAPTURE_ARTIFACT_SMOKE_ATTEMPTS:-2}"
export MA_NATIVE_CAPTURE_SMOKE_DURATION_SECONDS="${MA_NATIVE_CAPTURE_SMOKE_DURATION_SECONDS:-3}"
export MA_NATIVE_CAPTURE_SMOKE_TIMEOUT_SECONDS="${MA_NATIVE_CAPTURE_SMOKE_TIMEOUT_SECONDS:-120}"
export MA_NATIVE_CAPTURE_SMOKE_SYSTEM_AUDIO="${MA_NATIVE_CAPTURE_SMOKE_SYSTEM_AUDIO:-false}"
export MA_NATIVE_CAPTURE_SMOKE_MICROPHONE_AUDIO="${MA_NATIVE_CAPTURE_SMOKE_MICROPHONE_AUDIO:-false}"

./platform/e2e/native-capture-artifact-smoke.sh

echo "release native capture artifact smoke passed."
